### ISSUE TITLE
Midori 9.0 unusable because shortcut 'Search'

### ISSUE THREAD

**Issue by homezappa** [midori-browser/core#397] opened 2020-01-27 19:51 UTC
Midori 9.0, Manjaro Linux, kernel linux 5.3.18.
I can't use Midori because of the 'forward slash' key moving cursor in "search on page" field
I can' find a way to disable shortcuts.
I can't write a whole url in the url bar .. if I write http: the following '/' is'nt written and the cursor goes to 'Search in page' field.
correct asap, please (ot tell how disable shortcuts!)

**Comment by asc-soc** [comment] 2020-01-27 19:58
This is a duplicate of #364 fixed in current master.

**Closed as completed** 2020-02-04 07:22 UTC
