### ISSUE TITLE
Can't enter an URL containing "/" characters into the address bar

### ISSUE THREAD

**Issue by intc** [midori-browser/core#386] opened 2019-11-13 12:19 UTC
One can paste an URL and it works fine. While typing in the URL and hitting "/" character will invoke a search box. Is this really intended? 

Couldn't find any setting to alter this behaviour.

This is Midori 9.0 on Xfce4 / Gentoo.

**Comment by cyborgyn** [comment] 2019-11-17 19:33
The same here, with Midori 9.0 on Lxde / Gentoo, Alpha EV68 CPU. Also, not finding place/settings/extension to remove this "/" being a shortcut.

**Comment by asc-soc** [comment] 2019-11-17 20:47
This is a duplicate of issue #364, fixed in pull request #366.

**Closed as completed** 2019-12-02 15:19 UTC
